In [100]:
import numpy as np
import pandas as pd
from sklearn import datasets

iris = datasets.load_iris()
print(type(iris))

<class 'sklearn.utils.Bunch'>


In [101]:
x = iris.data
y = iris.target

In [102]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=123)

In [103]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=9)

knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=9)

In [104]:
y_pred = knn.predict(X_test)

y_pred

array([1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2,
       2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 1, 2])

In [105]:
y_test

array([1, 2, 2, 1, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 2, 2,
       2, 2, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 1, 2])

In [106]:
knn.score(X_test, y_test)

0.9666666666666667

In [107]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[22  0  0]
 [ 0 16  0]
 [ 0  2 20]]


In [108]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       0.89      1.00      0.94        16
           2       1.00      0.91      0.95        22

    accuracy                           0.97        60
   macro avg       0.96      0.97      0.96        60
weighted avg       0.97      0.97      0.97        60



# grid search

In [109]:
from sklearn.model_selection import GridSearchCV

parameters = {"n_neighbors": range(1, 50)}

gridsearch = GridSearchCV(KNeighborsClassifier(), parameters)

gridsearch.fit(X_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 50)})

In [110]:
gridsearch.best_params_

{'n_neighbors': 3}

In [111]:
y_pred = gridsearch.predict(X_test)

In [112]:
print(confusion_matrix(y_test, y_pred))

[[22  0  0]
 [ 0 15  1]
 [ 0  1 21]]


In [113]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       0.94      0.94      0.94        16
           2       0.95      0.95      0.95        22

    accuracy                           0.97        60
   macro avg       0.96      0.96      0.96        60
weighted avg       0.97      0.97      0.97        60



# logistic regression

In [114]:
import pandas as pd

the_path = r"C:\Users\12489\Documents\Data\diabetes.csv"
pima = pd.read_csv(the_path)
pima.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [115]:
feature_cols = ['Pregnancies', 'Glucose', 'BloodPressure', 'Insulin', 'BMI', 'Age']

X = pima[feature_cols].values
y = pima.Outcome.values

In [116]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [117]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

In [118]:
print(confusion_matrix(y_test, y_pred))

[[109  21]
 [ 23  39]]


In [119]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.84      0.83       130
           1       0.65      0.63      0.64        62

    accuracy                           0.77       192
   macro avg       0.74      0.73      0.74       192
weighted avg       0.77      0.77      0.77       192

